### ISSUE TITLE
[ContractInvariantMethod] should suppress CA1822

### ISSUE THREAD

**Issue by tom-englert** [SergeyTeplyakov/ReSharperContractExtensions#51]
When defining the first invariant of a class, the [ContractInvariantMethod] is added. It would be very helpful if the method had the attribute to suppress CA1822, like we get it when using the CIM code snippet:
        [ContractInvariantMethod]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Justification = "Required for code contracts.")]
        private void ObjectInvariant()
        {
        }

A nice to have would be the possibility to specify where the method is added (I prefer it to be at the end of the class)

**Comment by SergeyTeplyakov** [comment]
This is a good suggetion. I've added a configuration for the plugin that would contains those two options: place in the code and the need to add a SuppressMessage.

BTW, I'm intentially decided to put `ObjectInvariant` method right after constructor to make it more "descoverable".

**Comment by tom-englert** [comment]
Contracts are deprecated
