### ISSUE TITLE
For ReSharper 9 plugin is causing exception on every start. Duplicating confiugurable severity id 'Custom Warning for legacy contracts'

### ISSUE THREAD

**Issue by van800** [SergeyTeplyakov/ReSharperContractExtensions#55]
https://youtrack.jetbrains.com/issue/DEXP-55258

**Comment by SergeyTeplyakov** [comment]
Thanks. Will fix this.

**Comment by SergeyTeplyakov** [comment]
Should be fixed in latest release at https://github.com/SergeyTeplyakov/ReSharperContractExtensions/releases/tag/0.9.2.5
