### ISSUE TITLE
Extension not working in ReSharper 9.2

### ISSUE THREAD

**Issue by rancomarcus** [SergeyTeplyakov/ReSharperContractExtensions#56]
Hi Sergey, 

We have recently upgraded our ReSharper installation from version 9.1 to 9.2, but it seems that the Code Contract editing extension does not completely work in this version.

Please find below the steps to reproduce the issue:

[Create new Class project and in Class1 perform the following steps:]

1.	Create method Test1 with parameter ‘string s’,
2.	Type ‘Test2();’ in the method body and use Alt+Enter to open the Quick Fix menu (no menu is shown),
3.	Go to parameter s and use Alt+Enter to open the Quick Fix menu (no menu is shown, was expecting ‘add Contract.Requires’ action from Code Contracts extension in menu),
4.	Remove parameter s,
5.	Go to Test2 again and try to open the Quick Fix menu (works again).

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReSharperReproductionQuickFixBroken
{
    public class Class1
    {
        public void Test1(string s)
        {
            Test2();
        }
   }
}
```

I have also reported the issue to JetBrains, maybe the cause is on their side.

Please let me know if you need more information to reproduce the issue. It would be great if a fix would be provided, because the extension is really helpful to use. 

Thanks in advance!

Best regards,

Ranco Marcus

**Comment by rancomarcus** [comment]
Hi Sergey, 

Please see the response from JetBrains below:

> Thank you for the reply, Ranco!
> 
> Seems it’s really Code Contract editing extensions issue. There some internal changes implemented > in ReSharper 9.2, so extension just need to be updated.
> 
> Thank you.

Best regards,

Ranco Marcus

**Comment by rancomarcus** [comment]
Hi Sergey,

Could you please let us now if you are planning to support ReSharper 9.2 in the near future? 

We really got used to editing our contracts with the editing extension, but had to completely uninstall it in order not to break ReSharper's QuickFix feature. 

Please let me now if you need help reproducing this issue.

Best regards,
Ranco Marcus

**Comment by SergeyTeplyakov** [comment]
Everyone. I'll be working on the migration this weekend. Hope to finish this stuff in a couple of days.

**Comment by SergeyTeplyakov** [comment]
Should be fixed at https://github.com/SergeyTeplyakov/ReSharperContractExtensions/releases/tag/0.9.2.5

**Comment by rancomarcus** [comment]
Great, thanks a lot Sergey! I can confirm that the extension is now working properly on ReSharper 9.2.

**Comment by SergeyTeplyakov** [comment]
@rancomarcus No problem:) Sorry for the delay:)
