### ISSUE TITLE
Add or update contract class for 'Interface' is broken

### ISSUE THREAD

**Issue by tom-englert** [SergeyTeplyakov/ReSharperContractExtensions#58]
We always get the message `Cannot perform this action, most likely because of errors in the source code` - R# 9.2, both in VS2013 and VS2015.

**Comment by aetaylor** [comment]
Getting the same problem with VS2012 with R#9.1.1
But only on some PCs but not others - don't you hate those sort of bugs ;o)

**Comment by remyblok** [comment]
I have this issue too. I'm running VS2015 with R# 9.2.

**Comment by SergeyTeplyakov** [comment]
Will test with VS2015 after migration to 9.2. 
Started working on the migration:)

**Comment by SergeyTeplyakov** [comment]
I've tested with latest version (v.0.10.0.1) and this feature worked fine. Could you confirm or double check with latest version?

**Comment by tom-englert** [comment]
Contracts are deprecated
