### ISSUE TITLE
nameof() is not recognized as valid constant

### ISSUE THREAD

**Issue by remyblok** [SergeyTeplyakov/ReSharperContractExtensions#59]
With VS2015 and C# 6 i now use the nameof-operator a lot. Also in code contracts like:

Contract.Requires<ArgumentNullException>(typeOfSource != null, nameof(typeOfSource));

I now get squiggles  with the text: User messages to contract calls can only be string literals, or static field, or static property that is at least internally visible.

The nameof()-operator should be recognized as compile time static string. Thanks!

**Comment by SergeyTeplyakov** [comment]
Thanks a lot for bug report.

I'll add support for this feature soon.

**Comment by SergeyTeplyakov** [comment]
Fixed. Will release new version today or tomorrow.

Thanks for the bug report!

**Comment by SergeyTeplyakov** [comment]
Available at the latest release: https://github.com/SergeyTeplyakov/ReSharperContractExtensions/releases/tag/0.9.2.5
