### ISSUE TITLE
Not working at all in ReSharper 10

### ISSUE THREAD

**Issue by NameOfTheDragon** [SergeyTeplyakov/ReSharperContractExtensions#61]
None of the quick fixes show up at all in ReSharper 10.

Is support planned for ReSharper 10? I would like to know one way or another what the roadmap looks like.

Thanks.

**Comment by SergeyTeplyakov** [comment]
I don't have R# 10 so far. I do have my OOS license, so I'll ask JetBrains for update.

But I hope migration should be more straightforward that it was for R# 9.

**Comment by rancomarcus** [comment]
Hi Sergey,

Can you please provide a time frame when ReSharper 10 will be supported? We would like to upgrade to ReSharper 10, but would hate to loose this great extension. 

If I can be of any assistance, please let me know.

Best regards, Ranco

**Comment by eddievelasquez** [comment]
Is it safe to assume that this project has been abandoned?

**Comment by SergeyTeplyakov** [comment]
No it is not, but I'm working on other stuff right now. Will look at this soon.

And everyone can send a pull request with required changes:)

**Comment by eddievelasquez** [comment]
That is really good to know. I wish I had time to contribute. :-(

**Comment by SergeyTeplyakov** [comment]
Done. Released new version. You may find it here: https://resharper-plugins.jetbrains.com/packages/ReSharper.ContractExtensions/0.10.0.1

Or download (update) via R# gallery.

**Comment by SergeyTeplyakov** [comment]
Would be really gratefull if you'll double check that updated version is working fine (I've tested it myself) and close the issue if everything is OK.

**Comment by breki** [comment]
Tested it in VS 2013 with the latest R#, it seems to be working. Thank you very much, Sergey!

**Comment by rancomarcus** [comment]
That is great news. I too can confirm that the extension is working (VS 2013 Update 5 with ReSharper 10.0.2).

Thank you, Sergey!

**Comment by SergeyTeplyakov** [comment]
@breki, @rancomarcus Thanks guys. Closing the issue.
